 trigger:
 - develop

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'pipelines-poc-docker'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: Procurement_AzureCodeProject/Procurement_AzureCodeProject_Weather/Dockerfile